service: microservice-ecommerce-prices

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-existing-s3
  - serverless-domain-manager
  - serverless-iam-roles-per-function

params:
  default:
    api-domain: ${ssm:/st-marche/${sls:stage}/api/ecommerce-prices/api-domain}

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: st-marche-lambda-${sls:stage}
  stage: ${opt:stage, 'staging'}
  environment: ${file(./env.yml)}
  deploymentPrefix: ${sls:stage}
  deploymentBucket:
    name: br.com.marche.serverless.deploys
  apiGateway:
    apiKeys: ecommerce-prices-${sls:stage}
  tracing:
    apiGateway: true
    lambda: true

custom:
  customDomain:
    domainName: ${param:api-domain}
    stage: ${sls:stage}
    basePath: ecommerce
    autoDomain: false
  prune:
    automatic: true
    number: 3
  serverless-offline:
    noPrependStageInUrl: true
    useWorkerThreads: true
    apiKey: XPQS78EwIO86H8EZhJC7z4qww1cLolB06rIvIMFu
    prefix: ecommerce

functions:
  - ${file(./infra/lambda/import.yml)}

resources:
  - ${file(./infra/api-gateway/auth-response.yml)}

package:
  individually: true
  exclude:
    - __tests__/**
  patterns:
    - '!tmp/**'
    - '!package.json'
    - '!package-lock.json'
    - '!.editorconfig'
    - '!.vscode/**'
    - '!.github/**'
    - '!.git/**'
    - '!.nvmrc'
    - '!README.md'
    - '!env.yml'
